env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_BUCKET=hornblower-builds
  - secure: "xhZJS4Vm7hTjAEM0T6gfmY7U7JuX1fOmRVOLx631IMVOczMzPoj6s8bPJsLu1mCkQmA/YMIUKCBYraKzW7m+SREv179bUXveP1ZaxTv7+R8QDu1SffV9SwJ2BSyKJgvn+x1D3nbTC/qc2E/OM+bCxFEDhUJVKeNAcxEXgFFBXOqvp/SK7VsEpyS2qWF7rGQXhwjmXjgisX2yHfg1TUewyZsQFANXdE336C/IjMIRC62MEog2kDvcurXlcgnSg9/RBmACC3zDuYEzKlGiy8TnHnZ+0NzYMtbIkKFKbltfxjfzrILuOHbTA3x5X5U0oqmXjmixwd9n2CjscNYs1n5aS0UL7L5yzpHFSckS+KwFlV5cfm/6RFcSm/O3fJp4VQW5jaZGoYDJa4HlES5HOZ9rQ78/D8N+wiGfr0USjEXhFRgmMe306NbghSo7XEMFv2orOkmifwh46fG6kM9968UX5/tcFC5cvHFsDWC2vigKDv27p71EXffVfw1voBWLb7ud8VRDiUBh30GajByND1opL5qCx/ur/+3mHzPN5ZJlAaS5BtfdBImrsd9Wu7M4KkEg4X4Pd6zD/AuH2zygL53LFCBltTzQ66x8GouJWRZoX7rcJq6RkPm+jzrVmmHvxdUFQbrTL2rrx+RvlskqKhs7irPSy/BZuvSqrpDrcRdtOZU="
  - secure: "Xdxuu7Q1gt2QJyKNatZ8A34T6ehWi9q0XorayYAuHNDi587STuhiWauGyIO7XI9gdTd1pn2O45i0I/p0s40xela4oPOCHa018CRNBopJk6z0PrkwoVvXdEf6nS8vugsBcrg57MRvQMUr5Mx9fGrydMhLpJ4MqPWnB4HcLP0caO6QuTiPHgCnIV+CaYT65Sg+E8YK1C1rLOf9O541qZpvPaPHbQwzjQPmre2ITkaCF7CW+1jKLIVXy1XXlos1lVjchoLf/g9Xb8TDSSIBK9IOfQK+XlDxepMAe19RUIDrf3sFBNqcGuy1U1k/dkRuXFcxolf/h1Wnx4F27seRD5L3pFquKX4qVa07lmEcmgRxhbCo1kPP2m3uaxkUHgqIgxzZ/m8BTGCdsjj3Mcp/t/eMno3YrOL0e2QEN4PvHiul0kDgN2gh0H76AoPkakrTiZrPOFRCM/jK5TrWnImRSAs8hafxKDJDh0W0h6tM4Zbpb+g13rH94UsfwRP0YksnI85ooHT8GoS72Nwk9UeYYimf3mGtA17f8ZHGyK60p7LJNVhm9ejQfx60CrrjFuJqfmUw+7kMJwNFR9yPOICRAnmAKXL9nLjdLxbHiXb9Id2oo8WTawxuNH2x9B/pDTec1UVIYPEK7oEaRt37MRJuZO6lMGq0ck/76vg645KX46UTa0o="

language: php
php: 7.0
# Skip running any tests
script: phpunit --version

notifications:
  slack:
    secure: "c4Myu2VTuxy4o0l5FqGG9U0yMerKUjXBy1K4lnIwtPGhz8BXHzDuKggpbAfxKwi6q/BsQmqLL63bEh/9rhU6+2Hjpr6/tJgVKtNR/asRWXBeSDV7RgAjUv6M57PJxUkanNcHLSiHhtyNaPPDe7+eNf9f2GkndTzWW4y6fpc+TWX8uDbw+uFB+raZXN52BmxB7jWCLIaoO7B/C9FVdgvDeqhG5xBx/aQvXUpmxxi4d4JqIoBqUiWoy6sMJmow50TorlLrrx2Y2fGzSn44Ov+90nkgGF/jnPGTfD9AVTMHT6FwFIPOLVW9BnWszMnDlpqm7ua8Z0Z1pL2Nnika4OzlDowIEPATt3QtsxeUAwa0bmVMBqJvOWRaAQkiHQrEi19eddV/dHUCwjsXep1odGnSjZJP8AgkWNrI+6/CvsLqyUw/VHZIvfwaPWW+srGS9LFDRxLluw/VDcHcZoLO6GGzT/rLD4uCr0VhSX3YTHNWM86IRcgYRgEDLop9rluZOfRkb49Lhe4mCF9lfLqQAoG5kPo4AQZAvL7wBNI6GhzfYbzXiKUQtIUfHj14AV6zvS98Ur2k1ErYnPivgxrmRHWXFp3xGlJlEObME/81dr8aNQeqmRxDYiaOX1mst11xszg+UT7XdP0pTXJKaKELpL4E2iyLxom25AvHgaViFtDkVu8="

before_deploy:
  - pip install --user boto3
  - rm -rf "${TRAVIS_BUILD_DIR}"/.git

deploy:
- provider: script
  skip_cleanup: true
  script: python build_artifact.py staging
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: python build_artifact.py production
  on:
    branch: production
