env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_BUCKET=hornblower-builds
  - secure: "m9KKGw4I1tC8q8ZQ0FxzgR31o+lZJGhdo3D6vAwedpBNfUGWtP/09OhmaEvKG6UuRoFLh9IJqnvtvGN+QtaHz5p6B/7ro7MQVyD+ycty5dpRMhT1AcB3tRlRINcWqoLiuuAS0uocIFIQzZ7raSr66OHZ2pQ4tNRzccaW+VXtLweutG5/untRsNRMKSleV5CrfAnwps8Mvlf4Zf/EsVgCiv5qsAZENn5YbCSDRDz7M4kq92Cy1suIPs7eFThig3NybGrFlAIzfewja/dK+D+fGGFP7dBes1SQu30vkGHnNDcuYGQ7E9Oj+zqKO2gFhJij1hSrLKo9TjxvdT4w9VSBbCsi8sGnyheg2ULJL6CuoZplRsLfAdfyDI3xRwvT0xo/Ry61wpMVkXzpPAZQnamL5AEXZUvPIX8f8Aka/cNWynbI6pQ6TPUxwiaEO13y8Duph8a31IU4j82zYC785GhspjekTtphr3Rk6Bxaft8FuQvOnVHiEkN2x1FTbTHvyyDQImhNgtZ+2UUQP4mYVZU6SBUkXpbhM0sW3iFfMzALKg4EOGrZYlHCnQTBz9iikfeoGBY5Vl2b5su/U7g9NDJgGEEWi5S2uAMrDGIu4zeDwqRj50zbk7Y7LcNdfHpOLxvxOsf2XhYrAAO8zIP86MwvWE3dwCOFp6YThbfCm5/BSZ4="
  - secure: "U12g+/MKwpJxG4lmabCUewtA+ALmBUczOinvHK055a8i7YgomoIyIbu8Q+ugf8ddSfnHoYAD9bpqRETY2BFs7IicvWcr6rXmoaoh2e9O9bWDCvRPcmmFe+ihiA8rs40fv6Ss1+jvG/j0Tr1ogtkawejjxCPXDvwp8cb8JQffZzSkFrD7X3BFrb1d31maRHLX63JqEhUUrbflU7lss9vDAxWTYogfVHxDw5UdG2OusQYn89/8hlqBOe2GUYN/4dIgspjsjhs5f8LyF0sxl9426yiZkDQG8W5mmK5Nyu1FnbtNJeJwdKcGZXSvKlnlo/pQO9wuQQ1w3TKlA+vDs1DRDSS8MbQh0X2+dlXeV/dverv9j46+xSqr8DJeTdHcXGKcdGoW7XsubEsOJzI2mGtbLG4s5ENZFjvpB+4Aehee9IVMlqGS8PXTZOunk7yY8TfyOj7cPYWK4+VPM+KmqqbjBHrU8iDydqajPdirq7M0P9hgM5CZp5tdzY+jt/bEj/LQ/boKX9vju82FPpx9BQD6criTg9cMfE9I669LZFGM76Vzn/P9qxGFPt8jMeZ6bURPzi9hWyg/WnQk239joqaVP3KlKz/5Tf8rz4ds2NFCL4Cpj0lhXuH5dxfAwmJ+jXknYMaW7Sq2lfzgT72AsISgK0wEkQ/QZwzuIOLPrMCM8eg="

language: php
php: 7.0
# Skip running any tests
script: phpunit --version

notifications:
  slack:
    secure: "h5c0SwppmtMoVBGn1jFnCL31+i/WHmeVDDgswFh1ovYOPu9aXMXHugHcLzjfLM2fhiVNbx0ANdXEcDbCuwsGVkAqlTZVwt3GxyivxoOPM/oVw6J0xfTu/e8pxOZyCke1P+cxNfIen1nPG5rWCBbzTGjfHsviKrJ2bx+WBSda9KrYUHN3iLeJMJ/neQmJGOFG/rUy3I+cuhBo04xS1D+VUS4CxVR+FBOhnyTJu/ZAHIlyixmso6fi7c73xfz9HD8SZaiOqBsg8hT8ycPiSDL8QF/H+ewlQwkCh7mxqk8jThIMr16//aD9VwdI9fNcvdgGtlKMxyfkDhNAKkkc/1r+O779I89JXq+MU5Og+kCiGuk/ExdeKP0tdb/koqEjwd7kWpLOFQJEcpveOvCpibJ/vPMgmwiL3zHoFovEC90cNIi77Mz/+wDb4yeHOhs0ZdQL1yy1ybxUv+5kxs6fac/X5IDSyzZFgwRIBfiYdiit9aehep6JDhDdCGMX5N5XKY3QPOeTJ93eUuTSrRMzJ41kinjCEBOcl6OQoWP3aANcsuD+JzHbLRSeMlCTAN5AjMWQM9um80iKQY7DBzeZO1QOsRK96OFo6nUsTboG8EyGmyQGUDWp/huvsKosD3vnvaP1E7NLfEItu1JA85nJC9aXaCpgL9TIjBv8/flA23gN4A0="

before_deploy:
  - pip install --user boto3

deploy:
- provider: script
  skip_cleanup: true
  script: python build_artifact.py staging
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: python build_artifact.py production
  on:
    branch: production
