env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_BUCKET=hornblower-builds
  - secure: "B0wCRd1D65SqUSp2ohKPfkGUvzS02u4lGNf0bY2PPUtx7+mfrY6iIIJ9569U5TAHbVwzUUw+DqfRLsSeexzgK9mIWjFAvUdHnzVx2RzSLjIIWF90Ox/pPNyKYf9wOjzeNasfLwDZQvvuEfnf/lgDHt++OWCpMTABUQctGWDkdEj55AFqNad+m0Vtpc3420VoDbKbvkZNPV51njXe6vrXIQqffDTEKaQFc+GP7mtOa0C8Y9f7VomW1acT9VpCvLI09U/RrvXtQSs38LfucmNqYPtFRAbUCOUJ9He5Q/wfzyFosLk0NlL0xjYCd27/aTQRf5xSIO+psMba8heFqfZ7VlUmR5u9JRrxJC+eNXVPCx6D8EiEqEnbRxh3CQjzPGe2bvKcq9OuUFZ4jUM2STfl1PU6K1cjFSbZxqKo1NbPkUTL4REJ7QXiMuKQg0GeUs0n6KPHj+ry5ttE3CdR7yxjhzWfhFN6dMUzCcH7o8M216MMFHIuo0mLt4I1g7DqqrxryZJ+akqi4Mk0smHQlq7/l/6HMCQDQK9dDw74xr+jOvNWsl31VAJn8z1Yk0Y8czWviEmuGvkRjOyLbelbIEO2tg0nZpnFeIBPoq+ZdZ8gTV6cdx7f5WCVkg4C/RMluqqel0FXoDUGTauyG29FeHYFLcJlkAfNnZfX9Q1yjSpOLjI="
  - secure: "lF7M+IP0MjPZ8CYza9lUc9qmQ1duU2PF2UCQuQ+x9VgxCfuCHvGIhSljfOQCHm0BxA3Zj8wTs8KPzGCCjdR1C/sp3Pz7Eq1xjeyEjF5kWZ9jwmrRUZXMpOnGxcVJg2/nrT+AoROIsPyKI2W2Jm3b8gUcreMmLrHVsJr5R0uYsCyHCjmNJMDr03FKY9lf4QtEblRjs4R+EpK1U9IbYl3A+d6MqNBDR0PiExh0Jim3bbR9CjG1tzYnM5aDs/f1dXvUhi8CQDluiTh9DbJ8FFPznmBhIizYAuCJy5rEqfh1CTQCiE61a7de25a5KZ8V3Jvg4SgaERaGb4jx5G+p48wmWBtOGmHcNERvB8sAAwQL/PsuSY4OaQDFKfaQQ8XYZXKP8sbIZ6LHREYX4Zj4YcWhrviwgGgop9bqfz7mwdZVAxr91K3PJ+e6TrlK909UBEVL4AjV65eW/gkvcZI7YxdBRCYjFQXI8Q/2Pk1E6naU4SHotfbkcbJepBj46iA1BLLfHzXvHu4zLsLRcOmRu/qu4xgYSv+bMf9S9HlbawKfIkdh/Akl4Umtoovd/ua4pEO5aIuijqouT68BOfYXaSKcoi7NH3q6EqkD/XrQFohzvLF04HGQpzp/CRizzcLKmpSyAW10QefoFRW8BXBx0rWu10dKwus3vBj7S3xCOAZejVY="

language: php
php: 7.0
# Skip running any tests
script: phpunit --version

notifications:
  slack:
    secure: "h5c0SwppmtMoVBGn1jFnCL31+i/WHmeVDDgswFh1ovYOPu9aXMXHugHcLzjfLM2fhiVNbx0ANdXEcDbCuwsGVkAqlTZVwt3GxyivxoOPM/oVw6J0xfTu/e8pxOZyCke1P+cxNfIen1nPG5rWCBbzTGjfHsviKrJ2bx+WBSda9KrYUHN3iLeJMJ/neQmJGOFG/rUy3I+cuhBo04xS1D+VUS4CxVR+FBOhnyTJu/ZAHIlyixmso6fi7c73xfz9HD8SZaiOqBsg8hT8ycPiSDL8QF/H+ewlQwkCh7mxqk8jThIMr16//aD9VwdI9fNcvdgGtlKMxyfkDhNAKkkc/1r+O779I89JXq+MU5Og+kCiGuk/ExdeKP0tdb/koqEjwd7kWpLOFQJEcpveOvCpibJ/vPMgmwiL3zHoFovEC90cNIi77Mz/+wDb4yeHOhs0ZdQL1yy1ybxUv+5kxs6fac/X5IDSyzZFgwRIBfiYdiit9aehep6JDhDdCGMX5N5XKY3QPOeTJ93eUuTSrRMzJ41kinjCEBOcl6OQoWP3aANcsuD+JzHbLRSeMlCTAN5AjMWQM9um80iKQY7DBzeZO1QOsRK96OFo6nUsTboG8EyGmyQGUDWp/huvsKosD3vnvaP1E7NLfEItu1JA85nJC9aXaCpgL9TIjBv8/flA23gN4A0="

before_deploy:
  - pip install --user boto3
  - rm -rf "${TRAVIS_BUILD_DIR}"/.git

deploy:
- provider: script
  skip_cleanup: true
  script: python build_artifact.py staging
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: python build_artifact.py production
  on:
    branch: production
