env:
  global:
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_BUCKET=hornblower-builds
  - secure: "vcmvsu/pYNZZWlPwpDAtmW4mn6K77SNkoC5TYmfxUKQD5Z41Ly3JLFXY+5eWZ9+SqdbDXflQvGIo1j8hNRgRmEUdcuGZgbtlPQjtL4IwhbPEnFJDtsk4zWntOlEDCOspEpFl/Sbo42VTHeXedSOqDi2dUki/xvo3vkl6Z04cv34hiGPlWI5Vj91BwUKlpGw2j4L9XA2r0s8F0Viq2xU+TiMHblnhGKA649P52sexnchu/emnX1LuD6mbz8ipLn6ngsR7ztoLEYik6j5fqoDTcQfJhWVvBQBUNI47SbzNoLulLRaW3d3TWf2ejnEBH4giCiXd0062OIuOZAu4hV8F/OE/mP58ZGXlL463Ewrc0yT4sNstJ2clcv7ui5k24sjPqlBZz6lmKlt29w6Jla60mKA/pMSFYuGfXpxZwxBMUa0sV9PdZw9ZW8/3mdANAxMp7EGn62CCyqlJVUq69dEN13KKmX2WA6WPREebLnGd09p/ey9/aVzKow8keZfffTyJ4BtdNplTaCDs7vfkPeFCgZTAvX1YH7sSD6e0VEKdopiUKRdSZkMAGX5sc8F/x3TphIuBkpENuSFkbmTrdB5GHB9s/nmU6vN9HdLbBKz0Ig4S8+ElNzYc5gFkzwSf2qFd8LJEt2ISxOIbjRuqPbgWMPeXzEOW66lUXifq+0GW6yk="
  - secure: "N75nP65e7uYl253+FjBLBYb/7qdkidvGxf2rRwANescqLFNuRvUiHCwBocInuOx+ewD6CDFq9ZUXJI7jq8vn/4iLTN3u0R6zOY+hTUW8//0violntJqDwMcKjJrArasnbyUlFe1T3vDNiRrzRzybFTaJYDvZYGFqR95sl1aM3vzhYVrSftvjCgP8akoIyn6ThtUGtZMLpobIARVB6blQSciJnkEt1UsPQ3Vn723oVac6T6rcg8yXnKl0/YvQusDBOK8J0+9xqJOQspWmhDwMYt/hBqaNP+kjqI6LJVMXFskUoHi/s2bjW7QwQNm5ufv/M56KzCUsHJ8/vzGaIVKFjg4N45HfHmPUPjZt7brDcapq29nNEnGnmJkvLspoSSTA0vVSYOfLXr/eKlO32elR69BacLrC8MsdiWIEIrSBVT4GG92qQWbC84lTXHY0NJddZE8VxYOwZkDwKk8S5wTTh1uGavVNRobO/sMJ5tzBtnEXFTBt/9xJ3glMjl9YUTOdCG3VMNvoVO+pDnXLEhQTvj/XAPh5thvzrQX2Dcx1/rgtqaEOGPqaBHlan1b/XjZJAEon61kN38/XSwBBXaNZzRgINqj1FSW6L6PCTn7fFI2Zsa81p+BXU55tXewk3OggfcGZT7uE1CZo22H+Zi1f+pU/cVy/te1XldC+gk/15S0="

language: php
php: 7.0
# Skip running any tests
script: phpunit --version

notifications:
  slack:
    secure: "shEmGszZH5VpXjhn/HEY7/4JtyMgP4+GFEgPgyP1FAibBwQWepNjURG7zhcrwWCwCHPVOv33HRPRB6EXzRXCHTjiak7qGSgnYYcj5mjWid5I2LXiGXXAyCjdni4Mb3Q8MHC+7h1UyfbS0eQMfA7Z0ZkBUDHuvGN1xefgXNUpXxqMdDXTySEkAcGpQQm0OW63hXQuWSBPaYx2zCUPkNwj9gujOj0uBWfyTGsL2t+PJ34z2huBv0WAqasJC82qFFM38tfpEdwu/EuyQfFhI40d7BACtr47JIcWlbazQwx21TkY3sAwThcG4aKPgREuq8GTajmGmZLsL2ps6ZJJ4M1lDPC3JtiUnx8xDQ9JPRU3eIzwwrYttn4OOoMeBvyl/Nc8SBrPc548TEIiu5UYrX0VddIm2h9LT9nS5zMxEpJuFycTLcolGTzuZTUVX3ai7F0pjOs9oEyhiv9pCr7PRbdmMwsLw/Te73XYTjYomjTRYddmZRTwtAJr3bJdLKSdPYWDXB5OzesQeOFVc7jHviKq3OiNsGGeRjje9VvkB0EwVlUEFO5FGLF2yAkle88I3OE1w8WfjSneCQ1m3xc0U7F/O00oQ/7J24mHKlQtyruAiLrtuZCwC9rg2AD7TIZ1iwo0xmw5U9/2uGM/rMeeT0qyjkgojZr+dbrrEpvajytLVGU="

before_deploy:
  - pip install --user boto3
  - rm -rf "${TRAVIS_BUILD_DIR}"/.git

deploy:
- provider: script
  skip_cleanup: true
  script: python build_artifact.py staging
  on:
    branch: staging
- provider: script
  skip_cleanup: true
  script: python build_artifact.py production
  on:
    branch: production
