# This file is used to configure Fabric, not Travis CI

artifact_name: 'centaman-api-plugin'
# Valid values: plugin, theme, wp-content
artifact_type: 'plugin'

stages:
  stg:
    hosts: ['hnc-web01.stg.hbint.io']
    branch: 'staging'
  prod:
    hosts: ['hnc-web01.prod.hbint.io']
    branch: 'production'
